=== ahbuss/Simkit/src/simkit/xsd/translator/simkit.dtd
<!ELEMENT SimkitModule ( Comment*, Parameter*, StateVariable*, Event+ ) >
<!ATTLIST SimkitModule
        name            CDATA   #REQUIRED
	version		CDATA	#REQUIRED
>

<!ELEMENT Comment ( #PCDATA ) >

<!ELEMENT StateVariable  ( Comment )* >
<!ATTLIST StateVariable
	type        CDATA	#REQUIRED
	name        ID  	#REQUIRED
        shortName   CDATA       #IMPLIED
>

<!ELEMENT Argument ( Comment )* >
<!ATTLIST Argument
	type	    CDATA	#REQUIRED
        name        CDATA       #REQUIRED
>

<!ELEMENT Parameter ( Comment )* >
<!ATTLIST Parameter
	type        CDATA	#REQUIRED
	name        ID  	#REQUIRED
        shortName   CDATA       #REQUIRED
>

<!ELEMENT LocalVariable ( Comment )* >
<!ATTLIST LocalVariable
        type        CDATA       #REQUIRED
        name        CDATA       #REQUIRED
        value       CDATA       #REQUIRED
>

<!ELEMENT Event	( Comment*, Argument*, LocalVariable*, StateTransition*, (Schedule|Cancel)*, Coordinate? ) > 
<!ATTLIST Event
	name		ID	#REQUIRED
>

<!ELEMENT Coordinate EMPTY >
<!ATTLIST Coordinate 
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
>

<!ELEMENT Operation EMPTY >
<!ATTLIST Operation
        method  CDATA   #REQUIRED   
>

<!ELEMENT Assignment EMPTY >
<!ATTLIST Assignment
        value   CDATA   #REQUIRED
>

<!ELEMENT StateTransition ( Assignment|Operation ) >
<!ATTLIST StateTransition
        state           IDREF   #REQUIRED
>
  
<!ELEMENT EdgeParameter EMPTY >
<!ATTLIST EdgeParameter
        value   CDATA	#REQUIRED
>

<!ELEMENT Schedule ( EdgeParameter )* >
<!ATTLIST Schedule
	delay	CDATA	"0.0"
	event	IDREF	#REQUIRED
	condition CDATA	#IMPLIED 
        priority  CDATA  "0.0"	
>

<!ELEMENT Cancel ( EdgeParameter )* >
<!ATTLIST Cancel
	event	IDREF	#REQUIRED
	condition CDATA	#IMPLIED 	
>

=== ahbuss/Simkit/src/simkit/xsd/translator/ServerWithReneges.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ServerWithReneges.xml
    Created on : March 10, 2004, 1:19 PM
    Author     : Arnie Buss
    Author     : Rick Goldberg
    Description:
        Advanced Simkit application.
-->

<!--<!DOCTYPE SimkitModule PUBLIC '-//NPS Simkit//DTD Web Application//EN' 'http://blueoak.com/home/rmgold/CVS/Simkit/simkit/xsd/translator/simkit.dtd'>
-->
<SimkitModule
    name="ServerWithReneges"
    version="0.1.3" >

    <Parameter name="numberServers" type="int" shortName="servers" />
    <Parameter name="serviceTime" type="simkit.random.RandomVariate" shortName="service" />
    <Parameter name="renegeTime" type="simkit.random.RandomVariate" shortName="renege" />
    
    <StateVariable name="numberAvailableServers" type="int" />
    <StateVariable name="queue" type="java.util.LinkedList" />
    <StateVariable name="numberServed" type="int" />
    <StateVariable name="numberReneges" type="int" >
        <Comment>this state variable stores the number of reneges</Comment>
        <Comment>as a Java int.</Comment>
    </StateVariable>
    
    <Event name="Run" >
    
        <StateTransition state="numberAvailableServers" >
            <Assignment value="getNumberServers()" />
        </StateTransition>
    
        <StateTransition state="queue" >
            <Operation method="clear()"/>
        </StateTransition>
        
        <StateTransition state="numberServed" >
            <Assignment value="0" />
        </StateTransition>
        
        <StateTransition state="numberReneges" >
            <Assignment value="0" />
        </StateTransition>
        
    </Event>

    <Event name="Arrival" >
        
        <Argument name="customer" type="java.lang.Integer" />
        
        <StateTransition state="queue" >
            <Operation method="add(customer)" />
        </StateTransition>
        
        <Schedule event="Renege" delay="renegeTime.generate()" >
            <EdgeParameter type="java.lang.Integer" value="customer" />
        </Schedule>
        
        <Schedule event="StartService" delay="0.0" condition="getNumberAvailableServers() > 0" /> 
        
    </Event>
    
    <Event name="StartService" >
        
        <LocalVariable name="customer" type="java.lang.Integer" value="queue.first()" />
        
        <StateTransition state="queue" >
            <Operation method="removeFirst()" />
        </StateTransition>
        
        
        <StateTransition state="numberAvailableServers" >
            <Assignment value="numberAvailableServers - 1" />
        </StateTransition>
        
        <Cancel event="Renege" >
            <EdgeParameter type="java.lang.Integer" value="customer" />
        </Cancel>
        
        <Schedule event="EndService" delay="serviceTime.generate()" >
            <EdgeParameter type="java.lang.Integer" value="customer" />
        </Schedule>
        
    </Event>
    
    <Event name="EndService" >
    
        <Argument name="customer1" type="java.lang.Integer" />
        
        <StateTransition state="numberAvailableServers" >
            <Assignment value="numberAvailableServers+1" />
        </StateTransition>
        
        <StateTransition state="numberServed" >
            <Assignment value="numberServed+1" />
        </StateTransition>
        
        <Schedule event="StartService" condition="getNumberInQueue() > 0" priority="1.0" />
        
    </Event>
    
    <Event name="Renege" >
    
        <Argument name="customer2" type="java.lang.Integer" />
 
        <StateTransition state="queue" >
            <Operation method="remove(customer2)" />
        </StateTransition>
        
        <StateTransition state="numberReneges" >
            <Assignment value="numberReneges+1" />
        </StateTransition>
        
    </Event>
    
</SimkitModule>
