=== ahbuss/Simkit/src/simkit/xml/simkit.dtd
<!-- simkit.dtd	
        
       	based upon parts of LEGO.dtd
 
	1.  Useful for establishing root and content model. 
	2.  DTD can be used to autogenerate Schema to which restrictions
	can then be applied, if needed. See trang.jar
	3.  No tools go from Schema to DTD, however DTD is 
	used to autogenerate SAX parser code within netbeans.
        4.  DOM scanner autogenerated from DTD.
-->


<!ENTITY % VariableDeclarations " StateVariable | Parameter " >
<!ENTITY % EventGraph " (%VariableDeclarations;)* , (Event)+ " >
<!ENTITY % EdgeType " Schedule | Cancel " >
<!ENTITY % TransitionType " Assignment | Operation " > 
 
<!-- AKA LEGO -->
<!ELEMENT SimkitModule ( Comment*, %EventGraph; ) >
<!ATTLIST SimkitModule
        name            CDATA   #REQUIRED
	version		CDATA	#REQUIRED
>

<!ELEMENT Comment ( #PCDATA ) >

<!ELEMENT StateVariable  ( Comment )* >
<!ATTLIST StateVariable
	type        CDATA	#REQUIRED
	name        ID  	#REQUIRED
        shortName   CDATA       #IMPLIED
>

<!ELEMENT Argument ( Comment )* >
<!ATTLIST Argument
        type        CDATA       #REQUIRED
        name        ID          #REQUIRED
>

<!ELEMENT Parameter ( Comment )* >
<!ATTLIST Parameter
	type        CDATA	#REQUIRED
	name        ID  	#REQUIRED
        shortName   CDATA       #REQUIRED
>

<!ELEMENT LocalVariable ( Comment )* >
<!ATTLIST LocalVariable
        type        CDATA       #REQUIRED
        name        CDATA       #REQUIRED
        value       CDATA       #REQUIRED
>

<!ELEMENT Event	( Comment*, Argument*, LocalVariable*, StateTransition*, ( %EdgeType; )* ) > 
<!ATTLIST Event
	name		ID	#REQUIRED
>

<!ELEMENT Operation ( #PCDATA ) >
<!ATTLIST Operation
        method  CDATA   #REQUIRED   
>

<!ELEMENT Assignment ( #PCDATA ) >
<!ATTLIST Assignment
        value   CDATA   #REQUIRED
>

<!ELEMENT StateTransition ( %TransitionType; ) >
<!ATTLIST StateTransition
        state           IDREF   #REQUIRED
>
  
<!ELEMENT EdgeParameter EMPTY >
<!ATTLIST EdgeParameter
        value   CDATA   #REQUIRED
>

<!ELEMENT Schedule ( EdgeParameter )* >
<!ATTLIST Schedule
	delay	CDATA	"0.0"
	event	IDREF	#REQUIRED
	condition CDATA	#IMPLIED 
        priority  CDATA  "0.0"	
>

<!ELEMENT Cancel ( EdgeParameter )* >
<!ATTLIST Cancel
	event	IDREF	#REQUIRED
	condition CDATA	#IMPLIED 	
>

=== ahbuss/Simkit/src/simkit/xml/ServerWithReneges.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ServerWithReneges.xml
    Created on : March 10, 2004, 1:19 PM
    Author     : Rick Goldberg
    Description:
        Advanced Simkit application.
-->

<!DOCTYPE SimkitModule PUBLIC '-//NPS Simkit//DTD Web Application//EN' 'simkit.dtd'>
<SimkitModule
    name="ServerWithReneges"
    version="0.1.3" >

    <Parameter name="numberServers" type="int" shortName="servers" />
    <Parameter name="serviceTime" type="simkit.random.RandomVariate" shortName="service" />
    <Parameter name="renegeTime" type="simkit.random.RandomVariate" shortName="renege" />
    
    <StateVariable name="numberAvailableServers" type="int" />
    <StateVariable name="queue" type="java.util.LinkedList" />
    <StateVariable name="numberServed" type="int" />
    <StateVariable name="numberReneges" type="int" >
        <Comment>this state variable stores the number of reneges</Comment>
        <Comment>as a Java int.</Comment>
    </StateVariable>
    
    <Event name="Run" >
    
        <StateTransition state="numberAvailableServers" >
            <Assignment value="getNumberServers()" />
        </StateTransition>
    
        <!-- new translation tool:
        if StateTransition has no transition attribute, this is a one-or-more line operation,
        use the firePropertyChange with the state variable name instead of a parenthetical -->
        
        <StateTransition state="queue" >
            <Operation method="clear()"/>
        </StateTransition>
        
        <StateTransition state="numberServed" >
            <Assignment value="0" />
        </StateTransition>
        
        <StateTransition state="numberReneges" >
            <Assignment value="0" />
        </StateTransition>
        
    </Event>

    <Event name="Arrival" >
        
        <Argument name="customer" type="java.lang.Ingeger" />
        
        <StateTransition state="queue" >
            <Operation method="add(customer)" />
        </StateTransition>
        
        <Schedule event="Renege" delay="renegeTime.generate()" >
            <EdgeParameter  value="customer" />
        </Schedule>
        
        <Schedule event="StartService" delay="0.0" condition="getNumberAvailableServers() > 0" /> 
        
    </Event>
    
    <Event name="StartService" >
        
        <LocalVariable name="customer" type="java.lang.Integer" value="(Integer)queue.first()" >
        
        <StateTransition state="queue" >
            <Operation method="removeFirst()">
        </StateTransition>
        
        
        <StateTransition state="numberAvailableServers" >
            <Assignment value="numberAvailableServers - 1" />
        </StateTransition>
        
        <Cancel event="Renege" >
            <EdgeParameter value="customer" />
        </Cancel>
        
        <Schedule event="EndService" delay="serviceTime.generate()" >
            <EdgeParameter value="customer" />
        </Schedule>
        
    </Event>
    
    <Event name="EndService" >
    
        <Argument name="customer" type="java.lang.Integer" />
        
        <StateTransition state="numberAvailableServers" >
            <Assignmnet value="numberAvailableServers+1" />
        </StateTransition>
        
        <StateTransition state="numberServed" >
            <Assignment value="numberServed+1" />
        </StateTransition>
        
        <Schedule event="StartService" condition="getNumberInQueue() > 0" priority="1.0" />
        
    </Event>
    
    <Event name="Renege" >
    
        <Argument name="customer" type="java.lang.Integer" />
 
        <StateTransition state="queue" />
            <Operation method="remove(customer)" />
        </StateTransition>
        
        <StateTransition state="numberReneges" >
            <Assignment value="numberReneges+1" />
        </StateTransition>
        
    </Event>
    
</SimkitModule>

=== ahbuss/Simkit/src/simkit/xml/ArrivalProcessLite.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ArrivalProcessLite.xml
    Created on : February 27, 2004, 7:19 PM
    Author     : Rick Goldberg
    Description:
        Most basic Simkit application.
-->

<!DOCTYPE SimkitModule PUBLIC '-//NPS Simkit//DTD Web Application//EN' 'simkit.dtd'>
<SimkitModule
    name="ArrivalProcessLite"
    version="0.1" >

    <Parameter name="interarrivalTime" type="simkit.random.RandomVariate" shortName="tA" />
    <State name="numberArrivals" type="int" shortName="N" />

    <Event name="Run" >
        <StateTransition state="numberArrivals" transition="0" />
        <Schedule event="Arrival" delay="interarrivalTime.generate()" />
    </Event>

    <Event name="Arrival" >
        <StateTransition state="numberArrivals" transition="numberArrivals+1" />
        <Schedule event="Arrival" delay="interarrivalTime.generate()" />
    </Event>
    
</SimkitModule>
